const GET_RESTAURANTS_SAGA = 'GET_RESTAURANTS_SAGA';
const SET_RESTAURANTS = 'SET_RESTAURANTS';
const SET_PAGINATION = 'SET_PAGINATION';
const SET_FILTERS = 'SET_FILTERS';
const LEFT_PAGE = 'LEFT';
const RIGHT_PAGE = 'RIGHT';

export {
    GET_RESTAURANTS_SAGA,
    SET_RESTAURANTS,
    SET_FILTERS,
    SET_PAGINATION,
    LEFT_PAGE,
    RIGHT_PAGE
};